// Seed data: exercise library (strength / bodyweight / cardio / sport), starter foods,
// default routines, and the muscle-map taxonomy + curated recommendations.
// Food macros are typical per-serving values; the AI estimator and custom foods cover everything else.

// Muscle keys drive the Body map. 'full' = whole-body / cardio (shown as a pill, not painted).
export const MUSCLES = [
  ['chest', 'Chest'],
  ['shoulders', 'Shoulders'],
  ['biceps', 'Biceps'],
  ['triceps', 'Triceps'],
  ['forearms', 'Forearms'],
  ['core', 'Core & abs'],
  ['lats', 'Lats & mid-back'],
  ['traps', 'Traps & upper back'],
  ['lowerback', 'Lower back'],
  ['glutes', 'Glutes'],
  ['quads', 'Quads'],
  ['hamstrings', 'Hamstrings'],
  ['calves', 'Calves'],
];

export const EXERCISES = [
  // ── Strength: chest ─────────────────────────────────────────
  ['Bench Press', 'strength', 'chest', 'barbell'],
  ['Incline Bench Press', 'strength', 'chest', 'barbell'],
  ['Dumbbell Bench Press', 'strength', 'chest', 'dumbbell'],
  ['Incline Dumbbell Press', 'strength', 'chest', 'dumbbell'],
  ['Dumbbell Fly', 'strength', 'chest', 'dumbbell'],
  ['Cable Fly', 'strength', 'chest', 'cable'],
  ['Chest Press Machine', 'strength', 'chest', 'machine'],
  ['Pec Deck', 'strength', 'chest', 'machine'],
  // ── Strength: back ──────────────────────────────────────────
  ['Deadlift', 'strength', 'lowerback', 'barbell'],
  ['Romanian Deadlift', 'strength', 'hamstrings', 'barbell'],
  ['Barbell Row', 'strength', 'lats', 'barbell'],
  ['Dumbbell Row', 'strength', 'lats', 'dumbbell'],
  ['Lat Pulldown', 'strength', 'lats', 'cable'],
  ['Seated Cable Row', 'strength', 'lats', 'cable'],
  ['T-Bar Row', 'strength', 'lats', 'machine'],
  ['Face Pull', 'strength', 'traps', 'cable'],
  ['Shrug', 'strength', 'traps', 'dumbbell'],
  // ── Strength: legs ──────────────────────────────────────────
  ['Squat', 'strength', 'quads', 'barbell'],
  ['Front Squat', 'strength', 'quads', 'barbell'],
  ['Leg Press', 'strength', 'quads', 'machine'],
  ['Hack Squat', 'strength', 'quads', 'machine'],
  ['Bulgarian Split Squat', 'strength', 'quads', 'dumbbell'],
  ['Goblet Squat', 'strength', 'quads', 'dumbbell'],
  ['Walking Lunge', 'strength', 'quads', 'dumbbell'],
  ['Leg Extension', 'strength', 'quads', 'machine'],
  ['Leg Curl', 'strength', 'hamstrings', 'machine'],
  ['Hip Thrust', 'strength', 'glutes', 'barbell'],
  ['Calf Raise', 'strength', 'calves', 'machine'],
  ['Kettlebell Swing', 'strength', 'glutes', 'kettlebell'],
  // ── Strength: shoulders ─────────────────────────────────────
  ['Overhead Press', 'strength', 'shoulders', 'barbell'],
  ['Dumbbell Shoulder Press', 'strength', 'shoulders', 'dumbbell'],
  ['Arnold Press', 'strength', 'shoulders', 'dumbbell'],
  ['Lateral Raise', 'strength', 'shoulders', 'dumbbell'],
  ['Front Raise', 'strength', 'shoulders', 'dumbbell'],
  ['Rear Delt Fly', 'strength', 'shoulders', 'dumbbell'],
  ['Upright Row', 'strength', 'traps', 'barbell'],
  // ── Strength: arms ──────────────────────────────────────────
  ['Barbell Curl', 'strength', 'biceps', 'barbell'],
  ['Dumbbell Curl', 'strength', 'biceps', 'dumbbell'],
  ['Hammer Curl', 'strength', 'biceps', 'dumbbell'],
  ['Preacher Curl', 'strength', 'biceps', 'machine'],
  ['Cable Curl', 'strength', 'biceps', 'cable'],
  ['Close-Grip Bench Press', 'strength', 'triceps', 'barbell'],
  ['Skull Crusher', 'strength', 'triceps', 'barbell'],
  ['Triceps Pushdown', 'strength', 'triceps', 'cable'],
  ['Overhead Triceps Extension', 'strength', 'triceps', 'dumbbell'],
  ['Wrist Curl', 'strength', 'forearms', 'dumbbell'],
  // ── Strength: core ──────────────────────────────────────────
  ['Cable Crunch', 'strength', 'core', 'cable'],
  ['Weighted Sit-Up', 'strength', 'core', 'bodyweight'],
  ['Russian Twist', 'strength', 'core', 'dumbbell'],
  ['Ab Wheel Rollout', 'strength', 'core', 'bodyweight'],
  // ── Bodyweight / calisthenics ───────────────────────────────
  ['Push-Up', 'bodyweight', 'chest', 'bodyweight'],
  ['Diamond Push-Up', 'bodyweight', 'triceps', 'bodyweight'],
  ['Decline Push-Up', 'bodyweight', 'chest', 'bodyweight'],
  ['Pull-Up', 'bodyweight', 'lats', 'bodyweight'],
  ['Chin-Up', 'bodyweight', 'lats', 'bodyweight'],
  ['Dip', 'bodyweight', 'chest', 'bodyweight'],
  ['Inverted Row', 'bodyweight', 'lats', 'bodyweight'],
  ['Pike Push-Up', 'bodyweight', 'shoulders', 'bodyweight'],
  ['Handstand Push-Up', 'bodyweight', 'shoulders', 'bodyweight'],
  ['Bodyweight Squat', 'bodyweight', 'quads', 'bodyweight'],
  ['Jump Squat', 'bodyweight', 'quads', 'bodyweight'],
  ['Lunge', 'bodyweight', 'quads', 'bodyweight'],
  ['Pistol Squat', 'bodyweight', 'quads', 'bodyweight'],
  ['Glute Bridge', 'bodyweight', 'glutes', 'bodyweight'],
  ['Nordic Curl', 'bodyweight', 'hamstrings', 'bodyweight'],
  ['Plank', 'bodyweight', 'core', 'bodyweight'],
  ['Side Plank', 'bodyweight', 'core', 'bodyweight'],
  ['Hanging Leg Raise', 'bodyweight', 'core', 'bodyweight'],
  ['Crunch', 'bodyweight', 'core', 'bodyweight'],
  ['Mountain Climber', 'bodyweight', 'core', 'bodyweight'],
  ['Burpee', 'bodyweight', 'full', 'bodyweight'],
  ['Bear Crawl', 'bodyweight', 'full', 'bodyweight'],
  // ── Cardio ──────────────────────────────────────────────────
  ['Run', 'cardio', 'full', null],
  ['Treadmill Run', 'cardio', 'full', 'machine'],
  ['Walk', 'cardio', 'full', null],
  ['Incline Walk', 'cardio', 'full', 'machine'],
  ['Cycling', 'cardio', 'quads', null],
  ['Stationary Bike', 'cardio', 'quads', 'machine'],
  ['Rowing Machine', 'cardio', 'full', 'machine'],
  ['Stair Climber', 'cardio', 'glutes', 'machine'],
  ['Elliptical', 'cardio', 'full', 'machine'],
  ['Swimming', 'cardio', 'full', null],
  ['Jump Rope', 'cardio', 'calves', null],
  ['Hike', 'cardio', 'full', null],
  ['Sprint Intervals', 'cardio', 'full', null],
  // ── Sports & classes ────────────────────────────────────────
  ['Basketball', 'sport', 'full', null],
  ['Soccer', 'sport', 'full', null],
  ['Tennis', 'sport', 'full', null],
  ['Volleyball', 'sport', 'full', null],
  ['Boxing', 'sport', 'full', null],
  ['Martial Arts', 'sport', 'full', null],
  ['Yoga', 'sport', 'full', null],
  ['Pilates', 'sport', 'core', null],
  ['Climbing', 'sport', 'full', null],
  ['Skiing', 'sport', 'quads', null],
  ['Skateboarding', 'sport', 'full', null],
  ['Golf', 'sport', 'full', null],
  ['Dance', 'sport', 'full', null],
  // ── Mobility ────────────────────────────────────────────────
  ['Stretching', 'mobility', 'full', null],
  ['Foam Rolling', 'mobility', 'full', null],
];

// Curated fallback recommendations per muscle (used when AI isn't set up).
// [exercise name, scheme, why]
export const MUSCLE_RECS = {
  chest: [
    ['Bench Press', '3 × 6-10', 'The classic heavy presser — most total chest stimulus per set.'],
    ['Incline Dumbbell Press', '3 × 8-12', 'Fills in the stubborn upper chest with a deep stretch.'],
    ['Cable Fly', '3 × 12-15', 'Constant tension and a big squeeze without beating up your shoulders.'],
    ['Push-Up', '3 × max', 'No equipment, endlessly scalable — elevate feet to make it harder.'],
  ],
  shoulders: [
    ['Overhead Press', '3 × 5-8', 'The strength builder for the whole shoulder girdle.'],
    ['Lateral Raise', '4 × 12-20', 'Directly grows the side delts that make shoulders look wide.'],
    ['Rear Delt Fly', '3 × 15-20', 'Balances all your pressing and keeps shoulders healthy.'],
    ['Pike Push-Up', '3 × 8-12', 'Bodyweight pressing on the way to handstand push-ups.'],
  ],
  biceps: [
    ['Barbell Curl', '3 × 8-12', 'Load up both arms at once and progress the weight.'],
    ['Hammer Curl', '3 × 10-12', 'Hits the brachialis for thicker-looking arms.'],
    ['Chin-Up', '3 × 6-10', 'The heaviest curl you’ll ever do — your bodyweight.'],
  ],
  triceps: [
    ['Close-Grip Bench Press', '3 × 6-10', 'Heavy compound work for two-thirds of your arm size.'],
    ['Triceps Pushdown', '3 × 10-15', 'Easy on the elbows, great pump, simple to progress.'],
    ['Overhead Triceps Extension', '3 × 10-12', 'Stretches the long head — the part most people miss.'],
    ['Diamond Push-Up', '3 × max', 'Bodyweight option that torches all three heads.'],
  ],
  forearms: [
    ['Wrist Curl', '3 × 15-20', 'Direct forearm work for grip and size.'],
    ['Hammer Curl', '3 × 10-12', 'Builds the brachioradialis along the top of the forearm.'],
    ['Dumbbell Row', '3 × 8-12', 'Heavy holds double as grip training.'],
  ],
  core: [
    ['Plank', '3 × 45-60s', 'Anti-extension basics — the foundation of a strong trunk.'],
    ['Hanging Leg Raise', '3 × 8-15', 'Lower abs and hip flexors with a built-in grip bonus.'],
    ['Cable Crunch', '3 × 12-15', 'Abs grow like any muscle — this one you can load.'],
    ['Russian Twist', '3 × 20', 'Rotation work for the obliques.'],
  ],
  lats: [
    ['Pull-Up', '3 × 6-10', 'The king of upper-body pulling. Add weight when 10 gets easy.'],
    ['Barbell Row', '3 × 6-10', 'Heavy horizontal pulling for a thick mid-back.'],
    ['Lat Pulldown', '3 × 10-12', 'Perfect for controlled stretch and building toward pull-ups.'],
    ['Seated Cable Row', '3 × 10-12', 'Squeeze-focused rowing with constant tension.'],
  ],
  traps: [
    ['Face Pull', '3 × 15-20', 'Rear delts + mid traps — posture insurance for pressers.'],
    ['Shrug', '3 × 10-15', 'Direct upper-trap work, simple and effective.'],
    ['Upright Row', '3 × 10-12', 'Traps and side delts together — keep the pull to chest height.'],
  ],
  lowerback: [
    ['Deadlift', '3 × 3-6', 'The whole posterior chain in one lift. Master the hinge.'],
    ['Romanian Deadlift', '3 × 8-10', 'Loads the hinge with less fatigue than pulling from the floor.'],
    ['Glute Bridge', '3 × 12-15', 'Gentle posterior-chain work that spares the spine.'],
  ],
  glutes: [
    ['Hip Thrust', '3 × 8-12', 'The most direct glute loader there is.'],
    ['Bulgarian Split Squat', '3 × 8-12 each', 'Brutal and effective — big stretch under load.'],
    ['Kettlebell Swing', '3 × 15-20', 'Explosive hinge power with a conditioning kick.'],
    ['Glute Bridge', '3 × 15', 'No equipment needed to get the glutes firing.'],
  ],
  quads: [
    ['Squat', '3 × 5-8', 'The foundational leg builder — strength through a full range.'],
    ['Leg Press', '3 × 10-15', 'Push the quads hard without balancing a bar.'],
    ['Walking Lunge', '3 × 10 each', 'Single-leg strength, balance and a serious burn.'],
    ['Leg Extension', '3 × 12-15', 'Isolates the quads with a peak squeeze.'],
  ],
  hamstrings: [
    ['Romanian Deadlift', '3 × 8-10', 'The best stretch-loaded hamstring builder.'],
    ['Leg Curl', '3 × 10-15', 'Hits the knee-flexion half of the hamstrings’ job.'],
    ['Nordic Curl', '3 × 3-6', 'Bodyweight eccentric monster — sprint-injury armor.'],
  ],
  calves: [
    ['Calf Raise', '4 × 10-15', 'Full stretch at the bottom, pause at the top — no bouncing.'],
    ['Jump Rope', '3 × 2 min', 'Springy conditioning that quietly builds calves.'],
  ],
};

// [name, serving, calories, protein_g, carbs_g, fat_g, sugar_g]
export const FOODS = [
  // Proteins
  ['Chicken Breast (cooked)', '100 g', 165, 31, 0, 3.6, 0],
  ['Chicken Thigh (cooked)', '100 g', 209, 26, 0, 11, 0],
  ['Ground Beef 90/10 (cooked)', '100 g', 217, 26, 0, 12, 0],
  ['Steak (sirloin, cooked)', '100 g', 212, 29, 0, 10, 0],
  ['Salmon (cooked)', '100 g', 206, 22, 0, 12, 0],
  ['Tuna (canned in water)', '1 can (140 g)', 130, 29, 0, 1, 0],
  ['Shrimp (cooked)', '100 g', 99, 24, 0, 0.3, 0],
  ['Egg', '1 large', 72, 6.3, 0.4, 4.8, 0.2],
  ['Egg White', '1 large', 17, 3.6, 0.2, 0.1, 0.2],
  ['Turkey Breast (deli)', '100 g', 104, 17, 4, 2, 2],
  ['Bacon', '2 slices', 90, 6, 0.2, 7, 0],
  ['Tofu (firm)', '100 g', 78, 8, 2, 4.5, 0.6],
  ['Whey Protein', '1 scoop (30 g)', 120, 24, 3, 1.5, 2],
  ['Greek Yogurt (nonfat)', '170 g cup', 100, 17, 6, 0.5, 5],
  ['Cottage Cheese (2%)', '1/2 cup (113 g)', 90, 12, 5, 2.5, 4],
  // Carbs
  ['White Rice (cooked)', '1 cup (158 g)', 205, 4.3, 45, 0.4, 0.1],
  ['Brown Rice (cooked)', '1 cup (195 g)', 216, 5, 45, 1.8, 0.7],
  ['Pasta (cooked)', '1 cup (140 g)', 221, 8, 43, 1.3, 0.8],
  ['Bread (white)', '1 slice', 75, 2.6, 14, 1, 1.6],
  ['Bread (whole wheat)', '1 slice', 81, 4, 14, 1.1, 1.4],
  ['Bagel', '1 medium', 277, 11, 55, 1.4, 6],
  ['Tortilla (flour)', '1 large', 144, 4, 24, 3.6, 1],
  ['Oatmeal (dry)', '1/2 cup (40 g)', 150, 5, 27, 3, 1],
  ['Potato (baked)', '1 medium (173 g)', 161, 4.3, 37, 0.2, 2],
  ['Sweet Potato (baked)', '1 medium (114 g)', 103, 2.3, 24, 0.1, 7],
  ['Quinoa (cooked)', '1 cup (185 g)', 222, 8, 39, 3.6, 1.6],
  ['Cereal (frosted flakes)', '1 cup (41 g)', 154, 1.4, 37, 0.2, 15],
  ['Pancake', '1 medium (77 g)', 175, 5, 22, 7, 5],
  // Fruits & veg
  ['Banana', '1 medium', 105, 1.3, 27, 0.4, 14],
  ['Apple', '1 medium', 95, 0.5, 25, 0.3, 19],
  ['Orange', '1 medium', 62, 1.2, 15, 0.2, 12],
  ['Strawberries', '1 cup (152 g)', 49, 1, 12, 0.5, 7],
  ['Blueberries', '1 cup (148 g)', 84, 1.1, 21, 0.5, 15],
  ['Grapes', '1 cup (151 g)', 104, 1.1, 27, 0.2, 23],
  ['Avocado', '1/2 medium', 120, 1.5, 6, 11, 0.5],
  ['Broccoli (cooked)', '1 cup (156 g)', 55, 3.7, 11, 0.6, 2.2],
  ['Spinach (raw)', '2 cups (60 g)', 14, 1.7, 2.2, 0.2, 0.3],
  ['Mixed Salad + Vinaigrette', '1 bowl', 150, 3, 12, 10, 5],
  ['Carrots (raw)', '1 cup (128 g)', 52, 1.2, 12, 0.3, 6],
  // Fats, dairy & snacks
  ['Peanut Butter', '2 tbsp (32 g)', 188, 8, 8, 16, 3],
  ['Almonds', '1 oz (28 g)', 164, 6, 6, 14, 1.2],
  ['Olive Oil', '1 tbsp', 119, 0, 0, 13.5, 0],
  ['Butter', '1 tbsp', 102, 0.1, 0, 11.5, 0],
  ['Cheddar Cheese', '1 slice (28 g)', 113, 6.4, 0.9, 9.3, 0.1],
  ['Milk (2%)', '1 cup (244 g)', 122, 8, 12, 4.8, 12],
  ['Chocolate Chip Cookie', '1 medium', 78, 0.9, 10, 4, 6],
  ['Ice Cream (vanilla)', '1/2 cup (66 g)', 137, 2.3, 16, 7, 14],
  ['Dark Chocolate (70%)', '1 oz (28 g)', 170, 2.2, 13, 12, 7],
  ['Potato Chips', '1 oz (28 g)', 152, 2, 15, 10, 0.1],
  ['Protein Bar', '1 bar (60 g)', 210, 20, 23, 7, 14],
  ['Granola', '1/2 cup (61 g)', 298, 9, 32, 15, 12],
  // Meals & drinks
  ['Cheese Pizza', '1 slice', 285, 12, 36, 10, 4],
  ['Cheeseburger (fast food)', '1 burger', 540, 25, 40, 29, 9],
  ['Burrito (chicken)', '1 burrito', 620, 33, 68, 22, 4],
  ['Chicken Caesar Wrap', '1 wrap', 480, 28, 40, 22, 3],
  ['Sushi Roll (california)', '8 pieces', 255, 9, 38, 7, 6],
  ['PB&J Sandwich', '1 sandwich', 378, 12, 48, 16, 20],
  ['Orange Juice', '1 cup (248 g)', 112, 1.7, 26, 0.5, 21],
  ['Soda (cola)', '1 can (355 ml)', 139, 0, 39, 0, 39],
  ['Sports Drink', '20 oz bottle', 130, 0, 34, 0, 34],
  ['Coffee w/ Cream & Sugar', '1 cup', 60, 0.5, 8, 3, 7],
  ['Beer', '1 can (355 ml)', 153, 1.6, 13, 0, 0],
];

export const DEFAULT_ROUTINES = [
  {
    name: 'Push Day',
    items: ['Bench Press', 'Overhead Press', 'Incline Dumbbell Press', 'Lateral Raise', 'Triceps Pushdown'],
  },
  {
    name: 'Pull Day',
    items: ['Deadlift', 'Lat Pulldown', 'Barbell Row', 'Face Pull', 'Dumbbell Curl'],
  },
  {
    name: 'Leg Day',
    items: ['Squat', 'Romanian Deadlift', 'Leg Press', 'Leg Curl', 'Calf Raise'],
  },
  {
    name: 'Full Body (Home)',
    items: ['Push-Up', 'Pull-Up', 'Bodyweight Squat', 'Plank', 'Burpee'],
  },
];
